version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/automan"
    schedule:
      interval: "daily"
    target-branch: "develop"

