version: 1

update_configs:
  # to frontend
  - package_manager: "javascript"
    directory: "/front"
    update_schedule: "live"
    target_branch: "develop"

  # to backend
  - package_manager: "python"
    directory: "/automan"
    update_schedule: "live"
    target_branch: "develop"

